---
--- Generated by Luanalysis
--- Created by rolyfish.
--- DateTime: 2023/3/9 21:57
--- 可重入获取锁
--- 参数  哈希结构的key 、线程id、自动释放时间
---

local hkey = KEYS[1]
local threadID = ARGV[1]
local releaseTime = ARGV[2]
---- KEY不存在
if (redis.call('exists', hkey) == 0) then
    -- 设置重入次数为1,并设置过期时间
    redis.call('hset', hkey, threadID, '1');
    redis.call('expire', hkey, releaseTime);
    return 1;
end
---- key存在且是当前线程   hexists key field 判断哈希结构属性是否存在
if (redis.call('hexists', hkey, threadID) == 1) then
    redis.call('hincrby', hkey, threadID, '1');
    redis.call('pexpire', hkey, releaseTime);
end
return redis.call('pttl', hkey);