---
--- Generated by Luanalysis
--- Created by rolyfish.
--- DateTime: 2023/3/9 21:57
--- 可重入释放锁
--- 参数  哈希结构的key 、线程id
---

local hkey = KEYS[1]
local threadID = ARGV[1]
local releaseTime = ARGV[2]
-- KEY不存在
if (redis.call('hexists', hkey, threadID) == 0) then
    return nil;
end
-- key存在且是当前线程
local counter = redis.call('hincrby', hkey, threadID, -1);
if (counter > 0) then
    -- 重置有效期
    redis.call('pexpire', hkey, releaseTime)
    return 0;
else
    -- 释放锁
    redis.call('del', hkey)
    return 1;
end
return nil;
