spring:
  redis:
    #    host: 127.0.0.1
    host: 10.211.55.4
    port: 6379
    password: 123123
    #    SpringBoot默认使用lettuce实现,必须配置否则连接池不就生效
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间